### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by haya1300** [outsmartit/foundout6#1]
I have installd the template but it wont work and i can not find the index.php file

**Comment by outsmartit** [comment]
sorry, didn't catch that one.  index.php file had been added, you can copy it to your template

**Comment by haya1300** [comment]
Ok its words but i got also the massage: Waarschuwing
JFolder: :bestanden: Pad is geen map. Pad: G:\UwAmp\www\flexbox\templates\foundout6\css\
Whats the sulotion?
Also langeguage ini file is not working correct, look at pictiure.
![language-ini](https://cloud.githubusercontent.com/assets/10380110/19536311/c36ecb88-964b-11e6-83e6-6914e67d89c3.png)
