### ISSUE TITLE
nl-Nl ini file

### ISSUE THREAD

**Issue by haya1300** [outsmartit/foundout6#2]
Ok, its words now, but i get also the massage: Waarschuwing
JFolder: :bestanden: Pad is geen map. Pad: G:\UwAmp\www\flexbox\templates\foundout6\css\
Whats the sulotion?
Also langeguage ini file is not working correct, look at pictiure.

![language-ini](https://cloud.githubusercontent.com/assets/10380110/19550434/a6544718-96a9-11e6-8a22-2d3e69088a8f.png)

**Comment by outsmartit** [comment]
if you prefer to discuss in Dutch, feel free to do so.

Did you install the template via the Joomla installer or did you copy it in and have it discovered ?

Can you check in the folders if you have files in .. templates/foundout6/language/nl-NL ?  If not, can you copy them in (and create missing folders, that should fix the language issue.

The Folder error should not be blocking, but I look in to it tonight.   I need to redo a clean installation.

**Comment by haya1300** [comment]
Ik heb de template via ontdekken geïnstalleerd.
De taal bestanden staan wel in de juiste map.

**Comment by outsmartit** [comment]
Vreemd, ik heb daarnet een nieuwe Joomla installatie gedaan en de github files gedownload en bij mij werkt het.
Kan je wat gegevens geven over de omgeving waarop je werkt  : Windows, Wamp server vermoed ik, Joomla versie ? Dan probeer ik eens op een gelijkaardige omgeving.
De talen die je geïnstalleerd hebt zijn Dutch(nl-NL) en ook Engels.  Zou je kunnen nagaan of het in het werkt ?

**Comment by haya1300** [comment]
Ik heb het geïnstalleerd in UwWamp server Joomla 3.6 en met php versie 7.04
De laatste vraag is mij niet geheel duidelijk.

**Comment by haya1300** [comment]
Ook heb ik het net geïnstalleerd, ook via ontdekken, op XAMP, joomla versie 3.5.1, php 5.6.3 Data collatie utf8mb4_general_ci 
Met dezelfde problemen

**Comment by outsmartit** [comment]
probleem is het volgende :  als je download vanuit github krijg je een zip "foundout6-master".
Alvorens de template te installeren (via ontdekken) zou je de template folder moet hernoemen naar foundout6 (zonder master). Dat zou de problemen moeten verhelpen.

Het probleem is nu dat Joomla zoekt naar taalfiles ...tpl_foundout6-master.ini (kan je checken door in het algemeen controlepaneel de taaldebugging op te zetten en terug naar de template settings te gaan en dan te kijken naar de geladen (of net niet) geladen taalfiles).

Best is nu de template te verwijderen en vervolgens de template opnieuw in te kopiëren en de foldernaam aan te passen alvorens te installeren.

Zal het in de instructies opnemen.

**Comment by haya1300** [comment]
Ja het werkt nu perfect, ga morgen wel weer mee aan het stoeien en kijken of er wat van opsteek, vooral het flexbox gedeelte lijkt me intersant
Mijn dank voor zover
